import { HeartIcon, SearchIcon, UserCircleIcon } from "@heroicons/react/outline";

export const filters = [
  { icon: "/icons/islands.jpeg", name: "Islands" },
  { icon: "/icons/arctic.jpeg", name: "Arctic" },
  { icon: "/icons/design.jpeg", name: "Design" },
  { icon: "/icons/lake.jpeg", name: "Lake" },
  { icon: "/icons/countryside.jpeg", name: "Countryside" },
  { icon: "/icons/omg.jpeg", name: "OMG!" },
  { icon: "/icons/beach.jpeg", name: "Beach!" },
  { icon: "/icons/pools.jpeg", name: "Amazing Pools" },
  { icon: "/icons/amazingviews.jpeg", name: "Amazing Views" },
  { icon: "/icons/ryokans.jpeg", name: "Ryokans" },
  { icon: "/icons/yurts.jpeg", name: "Yurts" },
  { icon: "/icons/towers.jpeg", name: "Towers" },
  { icon: "/icons/skinout.jpeg", name: "Ski-in/out" },
  { icon: "/icons/iconiccities.jpeg", name: "Iconic Cities" },
  { icon: "/icons/boats.jpeg", name: "Boats" },
];

export const copyrightLinks = [
  { path: "#", title: "Privacy" },
  { path: "#", title: "Terms" },
  { path: "#", title: "Sitemap" },
  { path: "#", title: "Destinations" },
];

export const footerLinks = [
  {
    heading: "Support",
    subMenus: [
      { path: "#", title: "Help Center" },
      { path: "#", title: "AirCover" },
      { path: "#", title: "Safety Information" },
      { path: "#", title: "Supporting people with disabilities" },
      { path: "#", title: "Cancellation options" },
      { path: "#", title: "Our COVID-19 Response" },
      { path: "#", title: "Report a neighborhood concern" },
    ],
  },
  {
    heading: "Community",
    subMenus: [
      { path: "#", title: "Airbnb.org: disaster relief housing" },
      { path: "#", title: "Support Afghan refugees" },
      { path: "#", title: "Combating discrimination" },
    ],
  },
  {
    heading: "Hosting",
    subMenus: [
      { path: "#", title: "Try hosting" },
      { path: "#", title: "AirCover for Hosts" },
      { path: "#", title: "Explore hosting resources" },
      { path: "#", title: "Visit our community forum" },
      { path: "#", title: "How to host responsibly" },
    ],
  },
  {
    heading: "Airbnb",
    subMenus: [
      { path: "#", title: "Newsroom" },
      { path: "#", title: "Learn about new features" },
      { path: "#", title: "Letter from our founders" },
      { path: "#", title: "Careers" },
      { path: "#", title: "Investors" },
      { path: "#", title: "Gift cards" },
    ],
  },
];
export const mobileFooterLinks = [
  { path: "/", title: "Explore", icon: <SearchIcon className="w-6" /> },
  { path: "#", title: "Wishlist", icon: <HeartIcon className="w-6" /> },
  { path: "#", title: "Log in", icon: <UserCircleIcon className="w-6" /> },
];

export const listings = [
  {
    images: ["/island2.webp", "/island3.webp", "/island2.webp", "/island1.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 89,
    rating: 4.73,
    id: 1636475,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 50,
    rating: 4.5,
    id: 2352634,
  },
  {
    images: ["/island4.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 60,
    rating: 4.73,
    id: 336464745,
  },
  {
    images: ["/island3.webp", "/island1.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 98,
    rating: 4.5,
    id: 44636436,
  },
  {
    images: ["/island4.webp", "/island3.webp", "/island2.webp", "/island1.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 90,
    rating: 4.9,
    id: 5364643,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 70,
    rating: 4.0,
    id: 6856845,
  },
  {
    images: ["/arctic1.webp", "/arctic3.webp", "/arctic2.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 90,
    rating: 4.9,
    id: 785685,
  },
  {
    images: ["/arctic3.webp", "/arctic1.webp", "/arctic2.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 45,
    rating: 4,
    id: 858568,
  },
  {
    images: ["/arctic1.webp", "/arctic3.webp", "/arctic2.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 59,
    rating: 4.9,
    id: 9474845,
  },
  {
    images: ["/arctic3.webp", "/arctic1.webp", "/arctic2.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 100,
    rating: 4.0,
    id: 10856854,
  },
  {
    images: ["/design1.webp", "/design2.webp", "/design3.webp"],
    name: "6 bedroom duplex in ikoyi",
    location: "lagos, Nigeria",
    category: "Design",
    hostName: "Sunmi",
    availableDate: "Oct 24 - 27",
    price: 63,
    rating: 4.0,
    id: 1174865,
  },
  {
    images: ["/design3.webp", "/design1.webp"],
    name: "5 bedroom duplex in VI",
    location: "lagos, Nigeria",
    category: "Design",
    hostName: "Sunmi",
    availableDate: "Oct 24 - 27",
    price: 64,
    rating: 4.0,
    id: 125747,
  },
  {
    images: ["/design2.webp", "/design1.webp", "/design3.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Design",
    hostName: "Sunmi",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.0,
    id: 13745745,
  },
  {
    images: ["/design4.webp", "/design2.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Design",
    hostName: "Sunmi",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 14346464,
  },
  {
    images: ["/lake1.webp", "/lake2.webp", "/lake3.webp"],
    name: "6 bedroom duplex in ikoyi",
    location: "lagos, Nigeria",
    category: "Lake",
    hostName: "Nyerovwo",
    availableDate: "Oct 24 - 27",
    price: 63,
    rating: 4.0,
    id: 15356345,
  },
  {
    images: ["/lake2.webp", "/lake1.webp"],
    name: "5 bedroom duplex in VI",
    location: "lagos, Nigeria",
    category: "Lake",
    hostName: "Nyerovwo",
    availableDate: "Oct 24 - 27",
    price: 64,
    rating: 4.0,
    id: 1624237544,
  },
  {
    images: ["/lake3.webp", "/lake1.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Lake",
    hostName: "Nyerovwo",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.0,
    id: 173523457,
  },
  {
    images: ["/lake1.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Lake",
    hostName: "Nyerovwo",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 18242545758,
  },
  {
    images: ["/island2.webp", "/design1.webp", "/lake3.webp", "/design2.webp", "/arctic2.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Countryside",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 1956845435,
  },
  {
    images: ["/island1.webp", "/design2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "OMG!",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 2068688,
  },
  {
    images: ["/design2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Beach!",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 218568,
  },
  {
    images: ["/island2.webp", "/design2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Amazing Pools",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 22856856,
  },
  {
    images: ["/island4.webp", "/design2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Amazing Views",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 23343464,
  },
  {
    images: ["/design4.webp", "/design2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "3 bedroom duplex in VGC",
    location: "lagos, Nigeria",
    category: "Ryokans",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 2425235,
  },
  {
    images: ["/design2.webp", "/island4.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "4 bedroom duplex in Effurun",
    location: "Delta, Nigeria",
    category: "Yurts",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 2552352,
  },
  {
    images: ["/design4.webp", "/island4.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "4 bedroom duplex in Effurun",
    location: "Delta, Nigeria",
    category: "Towers",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 26255235,
  },
  {
    images: ["/design2.webp", "/island2.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "4 bedroom duplex in Effurun",
    location: "Delta, Nigeria",
    category: "Ski-in/out",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 2752352,
  },
  {
    images: ["/design1.webp", "/island4.webp", "/lake2.webp", "/design4.webp", "/arctic3.webp"],
    name: "4 bedroom duplex in Effurun",
    location: "Delta, Nigeria",
    category: "Iconic Cities",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 2825235,
  },
  {
    images: ["/design3.webp", "/island2.webp", "/lake3.webp", "/design4.webp", "/arctic3.webp"],
    name: "4 bedroom duplex in Effurun",
    location: "Delta, Nigeria",
    category: "Boats",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 87,
    rating: 4.0,
    id: 294242,
  },
];
