export const filters = [
  { icon: "/icons/islands.jpeg", name: "Islands" },
  { icon: "/icons/arctic.jpeg", name: "Arctic" },
  { icon: "/icons/design.jpeg", name: "Design" },
  { icon: "/icons/lake.jpeg", name: "Lake" },
  { icon: "/icons/countryside.jpeg", name: "Countryside" },
  { icon: "/icons/omg.jpeg", name: "OMG!" },
  { icon: "/icons/beach.jpeg", name: "Beach!" },
  { icon: "/icons/pools.jpeg", name: "Amazing Pools" },
  { icon: "/icons/amazingviews.jpeg", name: "Amazing Views" },
  { icon: "/icons/ryokans.jpeg", name: "Ryokans" },
  { icon: "/icons/yurts.jpeg", name: "Yurts" },
  { icon: "/icons/towers.jpeg", name: "Towers" },
  { icon: "/icons/skinout.jpeg", name: "Ski-in/out" },
  { icon: "/icons/iconiccities.jpeg", name: "Iconic Cities" },
  { icon: "/icons/boats.jpeg", name: "Boats" },
];

export const listings = [
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 93,
    rating: 4.73,
    id: 1,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.5,
    id: 2,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 93,
    rating: 4.9,
    id: 3,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Arctic",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.0,
    id: 4,
  },
  {
    images: ["/island1.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 93,
    rating: 4.73,
    id: 5,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.5,
    id: 6,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "5 bedroom duplex in ajah",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Fejiro",
    availableDate: "Oct 24 - 29",
    price: 93,
    rating: 4.9,
    id: 7,
  },
  {
    images: ["/island1.webp", "/island2.webp", "/island3.webp", "/island4.webp"],
    name: "3 bedroom bungalow in lekki",
    location: "lagos, Nigeria",
    category: "Islands",
    hostName: "Onome",
    availableDate: "Oct 24 - 27",
    price: 93,
    rating: 4.0,
    id: 8,
  },
];
